### ISSUE TITLE
Using it with Express?

### ISSUE THREAD

**Issue by slavafomin** [thedillonb/http-shutdown#8]
Hello!

Thank you for this great module! I've spent very hard time looking for solution of graceful shutdown.

However, I'm using Express, which provides access to server only after `listen()` is called.

It there a way to use this module with Express?

Thanks!

**Comment by thedillonb** [comment]
I haven't tried this myself, but I believe Express' `listen` is just a wrapper around `http.createServer` and `server.listen`:

```
app.listen = function() {
  var server = http.createServer(this);
  return server.listen.apply(server, arguments);
};
```

So, if I'm not mistaken, since `listen` should return the `http.Server` object, you should be able to do:

```
var express = require('express');
var httpShutdown = require('http-shutdown');

var app = express();
var server = httpShutdown(app.listen());

// sometime later
server.shutdown();
```

Double check this to be sure, but I believe it's possible. If not, again, Express' `listen` is just a wrapper around the `http.createServer` method which you can call directly and use this module like described in the readme.

**Comment by slavafomin** [comment]
Thank you for quick reply and a code example @thedillonb! I'm using it exactly as you've suggested here. I was just confused, because in your documentation it's said to use `httpShutdown()` **before** `server.listen()`, but in my case I'm actually using if **after**.
